# Run POI Unit Tests

trigger:
  branches:
    include:
      - '*'
    exclude:
      - main
  paths:
    include:
    - apis/poi/*

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: rununittest
  displayName: Run unit tests
  jobs:  
  - job: rununittest
    displayName: Run unit tests
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: UseDotNet@2
        displayName: dotnet install
        inputs:
          packageType: 'sdk'
          version: '2.1.504'
      - task: DotNetCoreCLI@2
        displayName: dotnet restore
        inputs:
          command: 'restore'
          projects: 'apis/poi/poi.sln'
          feedsToUse: 'select'
      - task: DotNetCoreCLI@2
        displayName: dotnet build
        inputs:
          command: 'build'
          projects: 'apis/poi/poi.sln'
      - task: DotNetCoreCLI@2
        displayName: dotnet test
        inputs:
          command: 'test'
          projects: 'apis/poi/tests/IntegrationTests/IntegrationTests.csproj'
          arguments: '--logger:trx'
  - job: createworkitem
    displayName: Create work item on failure
    dependsOn: rununittest
    condition: failed() # this job will only run if rununittest fails
    steps:
      - task: CreateWorkItem@1
        displayName: Create work item on failure
        inputs:
          workItemType: 'Issue'
          title: 'Build $(Build.BuildId) failed'
